# Generated by Django 3.2.5 on 2021-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYCCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('book_and_case', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=15)),
            ],
        ),
    ]
