# Generated by Django 3.2.5 on 2021-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namesapp', '0002_nyccurrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nycalready',
            name='id',
        ),
        migrations.AlterField(
            model_name='nycalready',
            name='book_and_case',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
