# Generated by Django 3.2.5 on 2021-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namesapp', '0003_auto_20210730_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nyccurrent',
            name='id',
        ),
        migrations.AlterField(
            model_name='nyccurrent',
            name='book_and_case',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
